// Centralized defaults for app-wide keyboard controls mapping.

export const keyboardControlsMap = {
	zoomIn: {
		keys: ['=', '+'],
		title: 'Zoom In',
		description: 'Zoom In the Media',
		action: 'zoomIn',
	},
	zoomOut: {
		keys: ['-', '_'],
		title: 'Zoom Out',
		description: 'Zoom Out the Media',
		action: 'zoomOut',
	},
	zoomTo100: {
		keys: ['0'],
		title: 'Zoom to 100%',
		description: 'Zoom to 100% [1:1]',
		action: 'zoomTo100',
	},
	zoomTo100Smaller: {
		keys: ['0', ')'],
		modifiers: ['shift'],
		title: 'Zoom to 100% (Smaller)',
		description: 'Zoom to 100% [1:1] (Smaller Dimension)',
		action: 'zoomTo100Smaller',
	},
	zoomToFit: {
		keys: ['1'],
		title: 'Zoom to Fit',
		description: 'Zoom to Fit',
		action: 'zoomToFit',
	},
	zoomToFill: {
		keys: ['1', '!'],
		modifiers: ['shift'],
		title: 'Zoom to Fill',
		description: 'Zoom to Fill',
		action: 'zoomToFill',
	},
	toggleToolLock: {
		keys: ['z'],
		title: 'Toggle Tool Lock',
		description: 'Toggle Tool Lock',
		action: 'toggleToolLock',
	},
	toolDividerHorizontal: {
		keys: ['h'],
		title: 'Horizontal Divider',
		description: 'Switch to Horizontal Divider Tool',
		action: 'toolDividerHorizontal',
	},
	toolDividerVertical: {
		keys: ['v'],
		title: 'Vertical Divider',
		description: 'Switch to Vertical Divider Tool',
		action: 'toolDividerVertical',
	},
	toolAutoMoveToggle: {
		keys: ['a'],
		title: 'Toggle Auto-Move',
		description: 'Toggle Auto-Move for Divider Tool',
		action: 'toolAutoMoveToggle',
	},
	toolAutoMoveDirection: {
		keys: ['a'],
		modifiers: ['shift'],
		title: 'Change Auto-Move Direction',
		description: 'Change Auto-Move Direction for Divider Tools',
		action: 'toolAutoMoveDirection',
	},
	toolBoxCutout: {
		keys: ['b'],
		title: 'Box Cutout Tool',
		description: 'Switch to Box Cutout Tool',
		action: 'toolBoxCutout',
	},
	toolCircleCutout: {
		keys: ['c'],
		title: 'Circle Cutout Tool',
		description: 'Switch to Circle Cutout Tool',
		action: 'toolCircleCutout',
	},
	toolOverlay: {
		keys: ['o'],
		title: 'Overlay Tool',
		description: 'Switch to Overlay Tool',
		action: 'toolOverlay',
	},
	toolSizeIncrease: {
		keys: [']'],
		title: 'Increase Tool Size',
		description: 'Increase Tool Size',
		action: 'toolSizeIncrease',
	},
	toolSizeDecrease: {
		keys: ['['],
		title: 'Decrease Tool Size',
		description: 'Decrease Tool Size',
		action: 'toolSizeDecrease',
	},
	swapVideos: {
		keys: ['tab'],
		// modifiers: ['shift'],
		title: 'Swap Media',
		description: 'Swap Left/Right or Inside/Outside or Top/Bottom Media Slots in the viewer',
		action: 'swapVideos',
	},
	openSettingsModal: {
		keys: [',', '<'],
		modifiers: ['ctrl'],
		title: 'Open Settings',
		description: 'Open Settings Modal',
		action: 'openSettingsModal',
	},
	videoPlayPause: {
		keys: ['space'],
		title: 'Play/Pause',
		description: 'Toggle Play/Pause',
		action: 'videoPlayPause',
	},
	videoFrameForward: {
		keys: ['arrowright'],
		title: '+1 Frame',
		description: 'Skip Forward One Frame',
		action: 'videoFrameForward',
	},
	videoFrameBackward: {
		keys: ['arrowleft'],
		title: '-1 Frame',
		description: 'Skip Backward One Frame',
		action: 'videoFrameBackward',
	},
	videoFrameForwardLarge: {
		keys: ['arrowright'],
		modifiers: ['shift'],
		title: '+10 Frames',
		description: 'Skip Forward 10 Frames',
		action: 'videoFrameForwardLarge',
	},
	videoFrameBackwardLarge: {
		keys: ['arrowleft'],
		modifiers: ['shift'],
        title: '-10 Frames',
		description: 'Skip Backward 10 Frames',
		action: 'videoFrameBackwardLarge',
	},
	videoMoveToStart: {
		keys: ['arrowleft'],
		modifiers: ['ctrl'],
        title: 'Go to Start',
		description: 'Move timeline to Start of Video',
		action: 'videoMoveToStart',
	},
	videoMoveToEnd: {
		keys: ['arrowright'],
		modifiers: ['ctrl'],
        title: 'Go to End',
		description: 'Move timeline to End of Video',
		action: 'videoMoveToEnd',
	},
    videoMoveToShorterStart: {
        keys: ['arrowleft'],
        modifiers: ['ctrl', 'shift'],
        title: 'Go to Start (Shorter)',
        description: 'Move timeline to Start of Shorter Video',
        action: 'videoMoveToShorterStart',
    },
    videoMoveToShorterEnd: {
        keys: ['arrowright'],
        modifiers: ['ctrl', 'shift'],
        title: 'Go to End (Shorter)',
        description: 'Move timeline to End of Shorter Video',
        action: 'videoMoveToShorterEnd',
    },
	videoToggleLoop: {
		keys: ['l'],
		title: 'Looping',
		description: 'Toggle Video Looping',
		action: 'videoToggleLoop',
	},
	videoIncreaseSpeed: {
		keys: ['.', '>'],
        title: '+ Speed',
		description: 'Increase Video Playback Speed',
		action: 'videoIncreaseSpeed',
	},
	videoDecreaseSpeed: {
		keys: [',', '<'],
        title: '- Speed',
		description: 'Decrease Video Playback Speed',
		action: 'videoDecreaseSpeed',
	},
	toggleControllerDocking: {
		keys: ['\\', '|'],
        title: 'Dock UI',
		description: 'Toggle Controller Docking Position',
		action: 'toggleControllerDocking',
	},
	closeLeftVideo: {
        keys: ['[', '{'],
		modifiers: ['ctrl', 'shift'],
        title: 'Close Left Video',
		description: 'Close Left Video',
		action: 'closeLeftVideo',
	},
	closeRightVideo: {
        keys: [']', '}'],
		modifiers: ['ctrl', 'shift'],
        title: 'Close Right Video',
		description: 'Close Right Video',
		action: 'closeRightVideo',
	},
    clearLocalSettings: {
		keys: ['c'],
        modifiers: ['ctrl', 'shift'],
        description: 'Clear Local Settings (Local Storage)',
        action: 'clearLocalSettings',
        hideInUI: true,
    },
};

export default keyboardControlsMap;
